name: Fetch and Process tta2

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python fetch_tta2.py

      - name: Commit and force-push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sonsstreams.m3u8
          git commit -m "Update tta2.txt" || echo "No changes to commit"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
